# Generated by Django 2.1.2 on 2018-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='script',
            field=models.TextField(null=True, verbose_name='Script'),
        ),
    ]
