# Generated by Django 2.1.2 on 2018-10-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url_sufix', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL Sufix')),
                ('code', models.TextField(verbose_name='Code')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Group', verbose_name='Group')),
                ('variables', models.ManyToManyField(blank=True, to='core.Variable', verbose_name='Variables')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='script',
        ),
        migrations.RemoveField(
            model_name='module',
            name='url_sufix',
        ),
        migrations.RemoveField(
            model_name='module',
            name='variables',
        ),
        migrations.AddField(
            model_name='module',
            name='scripts',
            field=models.ManyToManyField(to='core.Script', verbose_name='Scripts'),
        ),
    ]
