# Generated by Django 2.1.2 on 2018-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181031_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Code'),
        ),
    ]
