# Generated by Django 2.1.2 on 2018-10-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181031_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='variables',
            field=models.ManyToManyField(blank=True, to='core.Variable', verbose_name='Variables'),
        ),
    ]
