# Generated by Django 2.1.2 on 2018-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_module_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='request_method',
            field=models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PARAM')], default=1, verbose_name='Method'),
        ),
    ]
