# Generated by Django 2.1.2 on 2018-11-08 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181031_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(99)], verbose_name='Order')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Scripts',
                'verbose_name': 'Scripts',
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': 'Module', 'verbose_name_plural': 'Module'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Script', 'verbose_name_plural': 'Scripts'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['description', 'name', 'value'], 'verbose_name': 'Variable', 'verbose_name_plural': 'Variables'},
        ),
        migrations.AlterField(
            model_name='module',
            name='scripts',
            field=models.ManyToManyField(through='core.ModuleScript', to='core.Script', verbose_name='Scripts'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together={('name', 'value', 'request_method')},
        ),
        migrations.AddField(
            model_name='modulescript',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='modulescript',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Script', verbose_name='Script'),
        ),
        migrations.AlterUniqueTogether(
            name='modulescript',
            unique_together={('module', 'script')},
        ),
    ]
