# Generated by Django 2.1.2 on 2018-11-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181108_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulescript',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Module', verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='modulescript',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Script', verbose_name='Script'),
        ),
    ]
