# Generated by Django 2.1.2 on 2018-11-08 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181108_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulescript',
            name='order',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='modulescript',
            unique_together={('module', 'script'), ('module', 'order')},
        ),
        migrations.AlterModelTable(
            name='modulescript',
            table='core_module_scripts',
        ),
    ]
