# Generated by Django 2.1.2 on 2018-11-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181108_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulescript',
            options={'ordering': ['module', 'order'], 'verbose_name': 'Scripts', 'verbose_name_plural': 'Scripts'},
        ),
    ]
