# Generated by Django 2.1.2 on 2018-11-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181108_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.TextField(verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Codes',
                'ordering': ['name'],
                'verbose_name': 'Code',
            },
        ),
        migrations.AddField(
            model_name='modulescript',
            name='codes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Code', verbose_name='Code'),
        ),
    ]
