# Generated by Django 2.1.2 on 2018-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181109_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Util',
        ),
        migrations.AlterModelOptions(
            name='util',
            options={'ordering': ['name'], 'verbose_name': 'Util', 'verbose_name_plural': 'Utils'},
        ),
        migrations.RemoveField(
            model_name='modulescript',
            name='codes',
        ),
        migrations.AddField(
            model_name='script',
            name='utils',
            field=models.ManyToManyField(blank=True, to='core.Util', verbose_name='Utils'),
        ),
    ]
