# Generated by Django 2.1.2 on 2018-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181109_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='util',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
