# Generated by Django 2.1.2 on 2018-10-30 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('status', models.IntegerField(choices=[(1, 'Success'), (2, 'Fail')], verbose_name='Status')),
                ('date_checkpoint', models.DateTimeField(auto_now_add=True, verbose_name='Date Checkpint')),
            ],
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_execution_began', models.DateTimeField(null=True, verbose_name='Date Execution Began')),
                ('date_execution_finished', models.DateTimeField(null=True, verbose_name='Date Execution Finished')),
                ('checkpoints', models.ManyToManyField(to='execution.Checkpoint', verbose_name='Checkpoints')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='execution',
            name='keywords',
            field=models.ManyToManyField(to='execution.Keyword', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='execution',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='execution',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='execution',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Created'),
        ),
    ]
