# Generated by Django 2.1.2 on 2018-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_auto_20181030_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
