# Generated by Django 2.1.2 on 2018-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_auto_20181030_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='object',
            field=models.IntegerField(choices=[(1, 'MODULE'), (2, 'SCRIPT'), (3, 'OTHER')], null=True, verbose_name='Object'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='reference',
            field=models.IntegerField(choices=[(1, 'BEGIN'), (2, 'END'), (3, 'RUNTIME')], null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='date_checkpoint',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAIL')], null=True, verbose_name='Status'),
        ),
    ]
