# Generated by Django 2.1.2 on 2018-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_auto_20181031_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
