# Generated by Django 2.1.2 on 2018-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181031_2023'),
        ('execution', '0005_checkpoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='variables',
            field=models.ManyToManyField(blank=True, to='core.Variable', verbose_name='Variables'),
        ),
    ]
