# Generated by Django 2.1.2 on 2018-11-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_auto_20181031_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='date_execution_finished',
            field=models.DateTimeField(null=True, verbose_name='Date Finished'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='date_execution_started',
            field=models.DateTimeField(null=True, verbose_name='Date Started'),
        ),
    ]
