# Generated by Django 2.1.2 on 2018-11-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_auto_20181103_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='date_execution_finished',
            new_name='date_finished',
        ),
        migrations.RenameField(
            model_name='execution',
            old_name='date_execution_started',
            new_name='date_started',
        ),
    ]
