# Generated by Django 2.1.2 on 2018-11-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_auto_20181103_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='checkpoints',
            field=models.ManyToManyField(blank=True, to='execution.Checkpoint', verbose_name='Checkpoints'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='execution.Keyword', verbose_name='Keywords'),
        ),
    ]
