# Generated by Django 2.1.2 on 2018-11-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_auto_20181105_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['pk'], 'verbose_name': 'Checkpoint', 'verbose_name_plural': 'Checkpoints'},
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-pk'], 'permissions': (('can_execute', 'Can execute execution'), ('can_reexecute', 'Can re-execute execution')), 'verbose_name': 'Execution', 'verbose_name_plural': 'Execution'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['name'], 'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
    ]
