# Generated by Django 2.1.2 on 2018-11-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_auto_20181109_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='date_checkpoint',
            field=models.DateTimeField(verbose_name='Date Checkpoint'),
        ),
    ]
